### **Задание на повторение материала

**1)** Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

---
**2)** Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [9]:
a1_1 = a.reshape(2, 6)
a1_2 = a.reshape(3, 4)
a1_3 = a.reshape(4, 3)
a1_4 = a.reshape(6, 2)
a1_5 = a.reshape(12, 1)

---
**3)** Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [11]:
a2_1 = a.reshape(2, -1)
a2_2 = a.reshape(3, -1)
a2_3 = a.reshape(4, -1)
a2_4 = a.reshape(-1, 2)
a2_5 = a.reshape(-1, 1)

---
**4)** Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

#### Нет, т.к. у него 2 оси, вдоль которых индексируются элементы.


---
**5)** Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [16]:
b = np.random.randn(3, 4)
b

array([[ 0.14491568, -2.3789661 ,  0.43513453,  0.21297429],
       [ 0.58974781,  0.0759372 ,  0.93112616, -1.17631438],
       [ 0.27113705,  1.05706458,  0.1230062 ,  1.04326461]])

In [21]:
c = b.flatten()
c

array([ 0.14491568, -2.3789661 ,  0.43513453,  0.21297429,  0.58974781,
        0.0759372 ,  0.93112616, -1.17631438,  0.27113705,  1.05706458,
        0.1230062 ,  1.04326461])

---
**6)** Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [39]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

---
**7)** Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [44]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

*Массив а - одномерный, b - двухмерный (a.shape не равно b.shape)*

---
**8)** Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [65]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [66]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
v = np.concatenate((a, b), axis=0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
v.size

10

---
**9)** Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [72]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [74]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [75]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [76]:
B.size

16

*Вычислить обртаную матрицу для матрицы В не получится, потому что -* **np.linalg.det(B) = 0**

---
**10)** Инициализируйте генератор случайных числе с помощью объекта seed, равного 42

In [82]:
np.random.seed(42)

---
**11)** Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [84]:
c = np.arange(0, 16)

---
**12)** Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [85]:
C = c.reshape(4, 4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
D = B + C.dot(10)
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [93]:
D_det = np.linalg.det(D) # Определитель

In [94]:
D_rank = np.linalg.matrix_rank(D) # Ранг матирицы D

In [96]:
D_inv = np.linalg.inv(D) # обратная матрица
D_inv

array([[ 4.66062690e+13, -1.49229688e+13, -1.09972869e+14,
         7.82895692e+13],
       [ 1.63480451e+14, -3.81454387e+14,  2.72467419e+14,
        -5.44934838e+13],
       [-4.66779710e+14,  8.07677680e+14, -2.15016230e+14,
        -1.25881740e+14],
       [ 2.56692989e+14, -4.11300324e+14,  5.25216801e+13,
         1.02085655e+14]])

---
**13)** Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [103]:
D_inv[D_inv < 0], D_inv[D_inv > 0] = 0, 1
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.]])

In [104]:
E = np.where(D_inv, B, C)
E

array([[  5,   1,   2,  32],
       [ 14,   5,  86,   7],
       [  8,  86,  10,  11],
       [ 32,  13, 212, 302]])